CREATE DATABASE Bongani_POE

USE Bongani_POE
CREATE TABLE User_Details(
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
FULL_NAME VARCHAR(80) NOT NULL,
USERNAME VARCHAR(40) NOT NULL,
EMAIL VARCHAR(40) NOT NULL,
PASSWORD VARCHAR(40) NOT NULL
);

INSERT INTO User_Details
VALUES ('Administrator', 'Admin', 'admin@gmail.com', 'admin123');

USE Bongani_POE
CREATE TABLE Module_Details(
MODULE_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
MODULE_NAME VARCHAR(40) NOT NULL,
MODULE_CODE VARCHAR(10) NOT NULL,
WEEKLY_HOURS INT NOT NULL,
CREDITS INT NOT NULL
); 

USE Bongani_POE
SELECT * FROM User_Details;

USE Bongani_POE
SELECT * FROM Module_Details;


